### PR TITLE
A few updates, but mostly just an excuse to rerun CI...

### PR DESCRIPTION
**Pull request by xylar**
Checklist

- [ ] License file is packaged (see [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L57-L66) for an example)
- [ ] Source is from official source
- [ ] Package does not vendor other packages. (If a package uses the source of another package, they should be separate packages or the licenses of all packages need to be packaged)
- [ ] If static libraries are linked in, the license of the static library is packaged.
- [ ] Build number is 0
- [ ] A tarball (`url`) rather than a repo (e.g. `git_url`) is used in your recipe (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) for more details)
- [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there

### CODE REVIEW

**Comment by xylar** [comment]
It might be worth rebasing onto `conda-forge/staged-recipes/master` as well because I think a lot has likely changed.

**Comment by hobu** [comment]
@xylar please go ahead and carry this forward however you need.

**Comment by xylar** [comment]
I'm not able to do so.  I could make my own competing pull request but I don't have permission to edit yours.  That's why I'm making a PR to your branch/fork instead.  Would you like me to make a competing recipe instead, and you close yours?

**Comment by hobu** [comment]
Please go ahead and make a new one.

**Pull request closed without merging**
